# Travis-CI configuration file for VGMTrans
sudo: required
dist: trusty
language: cpp

matrix:
  include:
    # GCC7
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libglib2.0-dev
            - libfluidsynth-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      before_install:
        - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
        - sudo apt-get update -qq
        - sudo apt-get install qtbase5-dev
    # LLVM5
    - os: linux
      compiler: clang
      addons:
        apt:
          packages:
            - libglib2.0-dev
            - libfluidsynth-dev
      before_install:
        - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
        - sudo apt-get update -qq
        - sudo apt-get install qtbase5-dev
    # xcode7.3
#    - os: osx
#      before_install:
#        - brew upgrade qt || brew install qt
#        - brew upgrade fluid-synth || brew install fluid-synth

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
